batch_size: 16
epochs: 20
lr: 0.001
lr_decay: 0
num_layer: 3
emb_dim: 32
dropout_ratio: 0
JK: last
dataset: IMDB-BINARY
data_path: /home/shaoqi/DataSet/TU/
output_model_file: ''
gnn_type: gin
runseed: 6
num_workers: 8
aug1: dropN
aug2: dropN
aug_ratio: 0.3
loss_temp: 0.1
lamda: 0.1
task: tu
add_loop: True
headers: 1
debug: False
validate: False
save_folder: /home/shaoqi/code/HAGCL/logs
load_folder: 
pre_model_epo: 10
nmb_prototype: 2
