batch_size: 1
epochs: 20
lr: 0.01
lr_decay: 0
num_layer: 4
emb_dim: 512
dropout_ratio: 0
JK: all2
dataset: Citeseer
data_path: /home/shaoqi/DataSet/PD/
output_model_file: ''
gnn_type: gcn
runseed: 5
num_workers: 0
aug0: hete_none
aug1: dropN
aug2: dropN_node
aug_ratio: 0.4
loss_temp: 0.2
lamda1: 1
lamda2: 1
lamda3: 0
lamda4: 0.1
task: pd
add_loop: True
headers: 1
debug: True
validate: False
save_folder: /home/shaoqi/code/HAGCL_test/logs
load_folder: 
pre_model_epo: 10
nmb_prototype: 50
graph_pooling: mean
use_imp: False
val_lag: 5