batch_size: 128
epochs: 15
lr: 0.01
lr_decay: 0
num_layer: 3
emb_dim: 48
dropout_ratio: 0
JK: all2
dataset: PROTEINS
data_path: /home/shaoqi/DataSet/TU/
output_model_file: ''
gnn_type: gin
runseed: 9
num_workers: 8
aug0: hete_none
aug1: dropN
aug2: dropN
aug_ratio: 0.1
loss_temp: 0.2
lamda1: 1
lamda2: 1
lamda3: 1
lamda4: 0
task: tu
add_loop: True
headers: 1
debug: False
validate: False
save_folder: /home/shaoqi/code/HAGCL_test/logs
load_folder: 
pre_model_epo: 10
nmb_prototype: 2
graph_pooling: mean
use_imp: False
